### ISSUE TITLE
Generated permissions format

### ISSUE THREAD

**Issue by diazsasak** [bezhanSalleh/filament-shield#116]
Hi @bezhanSalleh ,

Any reason why it replace "_" with "::" ? the permission name looks weird. usually permission name is using snake case. 

like:

view_job_assigment instead of view_job::assignment

https://github.com/bezhanSalleh/filament-shield/blob/02a729b6c50499357ac55e24c62b0767a4966b0b/src/FilamentShield.php#L95

thanks

**Comment by bezhanSalleh** [comment]
Given that you are using this package i'm sure you are already a filament discord channel member.

So for future ref please ask your questions there on the shield channel instead of creating an issue.

This way, I won't have to close an issue and you would get your answer faster plus it will save our time.
