### ISSUE TITLE
Dashboard Permission Not Working

### ISSUE THREAD

**Issue by SkeyPunyapal** [bezhanSalleh/filament-shield#117]
only admin users have permission to see the dashboard but all users can see the dashboard even if they do have not any role. the widget was also having the same issue then I solved it with the manual assignment of permissions but I'm not able to find the way for the dashboard is there any way to manually assign the permission to the dashboard? because auto assignment is not working.

**Comment by bezhanSalleh** [comment]
Dashboard is basically a filament page, and for those we have `HasPageShield` otherwise look into the trait and build it yourself. mind you while generating permissions Dashboard page is excluded by default so you have to first remove it from shield config in order for shield to generate a permission for it.

and stop creating issues... as these sorta questions on shield's discord channel or filament server.
