### ISSUE TITLE
Translate Widget Label

### ISSUE THREAD

**Issue by miguelurtado** [bezhanSalleh/filament-shield#195]
It's possible translate or set the label of widgets in widgets tab?

![image](https://github.com/bezhanSalleh/filament-shield/assets/3810528/e0475c74-75f7-49bf-9de6-3f8bddcb2e84)

**Comment by miguelurtado** [comment]
What about change the function getLocalizedWidgetLabel()?

Of:
```
$heading = Str::of($widget)
            ->after(Utils::getPagePermissionPrefix().'_')
            ->headline();
```

To:
```
$heading = Lang::has("filament-shield::filament-shield.resource_permission_widget_label.$widget", app()->getLocale())
            ? __("filament-shield::filament-shield.resource_permission_widget_label.$widget")
            : Str::of($widget)->after(Utils::getWidgetPermissionPrefix() . '_')->headline();
```

**Comment by bezhanSalleh** [comment]
dude you are missing the point. the logic doesn't end there, it actually creates a default if none of the actually labels for widgets are defined. so based on the type of widget it get the label and how you provide the label is up to you i.e. if its translatable or not. and for StatsOverview widgets. you just have to define a public method that returns a translatable string because they don't come with a default heading of any sorts. but for table and chart widgets the already have headings. hope this makes it a little bit clear.
