### ISSUE TITLE
Do not write changes made by UI to config file.

### ISSUE THREAD

**Issue by danielbehrendt** [bezhanSalleh/filament-shield#21]
In terms of version control and automated deployments I thinks it's not the best practice that this packages writes/modifies the `config/filament-shield.php` file.

Any changes written there would be gone after a new code deployments. I think it's good to have config values as defaults from this file but not to store any changes made by UI in there.

Anyway, this package is great!

**Comment by bezhanSalleh** [comment]
as discussed on discord this would be a greate enhancement.
but it will be awhile to get it done.

**Comment by titantwentyone** [comment]
I just wanted to add that as Filament has recently deprecated how some elements are used I wondered if the Shield Filament Resource could be served from the package rather than stubbed into the project. I was just auditing my deprecated code and saw that `App\Filament\Resources\Shield\RoleResource\Pages\ListPages` uses `\Filament\Pages\Actions\ButtonAction` which should now use `\Filament\Pages\Actions\Action`. Thought the comment would be useful here rather than as a separate issue as kind of related.

I second the awesome package sentiment! :+1:

**Comment by bezhanSalleh** [comment]
@titantwentyone well be updating everything this week and thanks for the encouragement.
