### ISSUE TITLE
Access to undeclared static property Spatie\Permission\PermissionRegistrar::$pivotPermission

### ISSUE THREAD

**Issue by piotrh052b** [bezhanSalleh/filament-shield#272]
Hello,

This error occurs when I try to run php artisan shield:install --fresh or php artisan migrate:fresh

Can you help me with this ?

Shield version 3.0.11

**Comment by piotrh052b** [comment]
I'm sorry - it's my mistake. I left old migration file.

**Comment by Sjoerd24** [comment]
I have the same problem, can you elaborate on how you fixed it?

**Comment by mrailton** [comment]
Just want to add to this. The issue is because in 3.0.11 the author changed the laravel-permisison required from [spatie/laravel-permission](https://packagist.org/packages/spatie/laravel-permission): ^5.0 to [spatie/laravel-permission](https://packagist.org/packages/spatie/laravel-permission): ^5.0|^6.0. This causes composer to upgrade laravel-permission to v6.0 which has breaking changes mentioned in the upgrade log, specifically around migrations.
