### ISSUE TITLE
[QUESTION] Deployment after shield:generate

### ISSUE THREAD

**Issue by bomshteyn** [bezhanSalleh/filament-shield#292]
### Challenge
As we continue developing the application more resources, pages and widget are being added.

`shield:generate` can generate the missing policies and permissions. But what happens when we deploy to production?

While the policies are properly version controlled, the permissions are not. 
The `shield:seeder` is ok on initial install, but on continuous basis makes little sense in my opinion.

### Proposed Solution
I think a better solution would be to create migration file with permission changes and running that instead of directly adding the permission to the DB this was they can be automatically deployed,  rolled back and version controlled.

**Comment by bezhanSalleh** [comment]
I totally get it. but it widely depends on the type of project and it's hard to account for all the scenarios that's why i left the seeder option as is. Because some projects don't need anything at all.

1. I have projects where the current seeder option is enough
2. I have projects that the seeder is generated for a fixed number of roles and permissions plus a number of predefined users.
3. and i have projects that every month the permissions change and for those i just rename the seeder based on the version and append a `.archived` at the end so in case i need to rollback. i have a custom command that does it for me so i use that in ci/cd.

But if you can improve the existing scenario and make it optional! you are welcome to PR it.

**Comment by aeq-dev** [comment]
Dear @bezhanSalleh 
Could you please share with us the third case ?
How can we handle the new resources added in the future in production ? especially the new model policy file

**Comment by lukasinko** [comment]
I'm also missing some real world example of the typical deployment workflow. Would be really handy to follow some best practice.
