### ISSUE TITLE
Can I use this to show seperate panels based on roles

### ISSUE THREAD

**Issue by abishekrsrikaanth** [bezhanSalleh/filament-shield#301]
The discussions don't seem to be enabled on this repository, so posting the question here.

Can I use this package to show seperate panels based on roles?

**Comment by bezhanSalleh** [comment]
yeah, since most of people using shield is on filament discord server and shield has a dedicated channel the discussion for the repo is disabled.
So if you are on there post any questions you have there. might get answers faster. if not, could you give me a for instance. like how are you listing them now? if it's just about panels you might wanna checkout the [Panel Switch](https://github.com/bezhanSalleh/filament-panel-switch) plugin for filament. (will close it for now but you can still continue asking questions ... tnx)
