### ISSUE TITLE
Get localized page label (Argument #1 ($page) must be of type string, array given)

### ISSUE THREAD

**Issue by alihasnain01** [bezhanSalleh/filament-shield#337]
Hi,

Hope all you are doing well. I'm facing following issue 

BezhanSalleh\FilamentShield\FilamentShield::getLocalizedPageLabel(): Argument #1 ($page) must be of type string, array given, called in

![image](https://github.com/bezhanSalleh/filament-shield/assets/143272549/7307815f-2100-461b-bef3-ba8d686d4b91)

**Comment by magentix98** [comment]
Hi, I had the same issue after updating to filament V3. 
I guess you have published RoleResource.php using command "shield:publish". If you did not make any changes in RoleResource.php you can simple run "shield:publish" again and force overwrite RoleResource.php. Otherwise you will need to really your changes.

**Comment by alihasnain01** [comment]
Yes, you're correct. I've published the RoleResource.php file and implemented some modifications. What is the better solution if in future this issue encounter again as I can remember what things was modified.

**Comment by alihasnain01** [comment]
Thanks @micraux it is working fine now
