### ISSUE TITLE
the permission 'view' not work alone

### ISSUE THREAD

**Issue by OmarASharaf** [bezhanSalleh/filament-shield#41]
I need to give the user only the permission 'view' to show a specific Post on the view page but this does not work it shows a 403 error, to make it work I need to add the permission 'view any'

and I don't want to give the user the permission 'view any' to show all the posts

laravel => v9.11
filament => v2.11.10
filament-shield => v1.1

**Comment by bezhanSalleh** [comment]
not a shield issue, please refer to https://laravel.com/docs/9.x/authorization#writing-policies

**Comment by titantwentyone** [comment]
I came across the same issue and had to provide `view_any` for a resource when I wanted to test a delete method against.

Using @OmarASharaf's issue as an example, I think the logic here is that you wouldn't be able to access the ability to view an object in the UI without the ability to "view_any" (i.e. it is only available via the resource menu/table item in the UI). However you could get the URL to view a resource seperately and place it elsewhere - say, in a widget - but to do this, we have to provide the user with the ability to view all items in order to view a single instance. I think this is the way Filament deals with the policy internally rather than how Shield implements it.

As an aside, you can hide the resource menuitem by using:

```
public static function shouldRegisterNavigation() : bool
{
    return false;
}
```
This will hide the menu item but not the ability to view all records if you know the url.
