### ISSUE TITLE
Model permissions, not resources

### ISSUE THREAD

**Issue by lukeholder** [bezhanSalleh/filament-shield#415]
Forgive me if I am mistaken, but when the documentation refers to "Resources" are you just meaning Models?

I wanted to have 2 Filament resources that use the same model so I can split UI and permissions for interacting with that model - does Shield support that?

I can't seem to generate permission set for 2 different resources with the same Model underneath.

Thankyou for the package!

**Comment by bezhanSalleh** [comment]
No worries! "Resources" mean "Filament Resources". To handle your scenario extend your model instead of the default one. Suppose you have a `User` model with a `type` field and you have users with `type='agent'`, and you want to handle the UI and policies separately or maybe some other reason. Then
```php
use App\Models\User;

class Agent extends User
```
Create another resource using `Agent` as the model. so you will have
`UserResource` with `User` model
`AgentResource` with `Agent` model
Now Shield will generate the permissions and policies how you like.
Also look into the `shield:generate` command options if you have updated the policies or don't wanna overwrite them.
