### ISSUE TITLE
existing Models / Resources not showing 

### ISSUE THREAD

**Issue by miiiwdy** [bezhanSalleh/filament-shield#426]
I have a problem with filament shield where when I want to select the permissions of a role, filament shield only displays models from 
" Spatie\Permission\Models\Role ", while my other models do not appear in that selection

**Comment by miiiwdy** [comment]
![Uploading 1.png…]()
![Uploading image.png…]()

**Comment by bezhanSalleh** [comment]
As it states shield only generates permissions for filament components (Resources, Pages, Widgets). so if your models aren't utilized by resources shield won't touch 'em. So generate permissions and policies for them your self and then they will show up on the `Custom Permissions` tab in shield. if you want to have them grouped like `Resources` tab then you got to make resources for them. Shield will have an opt-in option for standalone models in the future but right now, i don't have the time to make it happen. Also if you could, these are basically questions and since you are on discord just ask them on the shield's channel to get a quick response. Thanks.
