### ISSUE TITLE
installing with tenant fails

### ISSUE THREAD

**Issue by Causeofhell** [bezhanSalleh/filament-shield#448]
Installing with tenant fails because is pushing uncompleted files, this happened in an existing project while updating the plugin
on existant proyect while updating and trying to config to tenant, commands 
`php artisan shield:setup --tenant=App\\Models\\Team` and `php artisan shield:install admin --tenant --generate-relationships `are modifying the panel provider, app service provider, filament-shield and permissions and is failing because is pushing wrong code destroying code structure or simply leaving an empty file
![Captura de pantalla 2024-11-14 233433](https://github.com/user-attachments/assets/928b939e-46f1-4e83-bb79-c455c8644c18)

In the picture you can see that is creating more than 2000 lines of nothing...

Also the command `php artisan shield:install --fresh` is not seeding the database like in the pass is only generating the files but not executing a migration or creating the user 

OS: Win 11
Filament: 3.2.91
code editor: vs code

**Comment by bezhanSalleh** [comment]
please provide 

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**please complete the following information:**
 - OS: [e.g. iOS]
 - Filament [e.g. 3.2]
 - Version [e.g. 2.2]

**Additional context**
Add any other context about the problem here.

**Comment by Causeofhell** [comment]
> please provide some context:
> 
> **Describe the bug** A clear and concise description of what the bug is.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Go to '...'
> 2. Click on '....'
> 3. Scroll down to '....'
> 4. See error
> 
> **Expected behavior** A clear and concise description of what you expected to happen.
> 
> **Screenshots** If applicable, add screenshots to help explain your problem.
> 
> **please complete the following information:**
> 
> * OS: [e.g. iOS]
> * Filament [e.g. 3.2]
> * Version [e.g. 2.2]
> 
> **Additional context** Add any other context about the problem here.

i updated with more information, sorry i was trying to find more info and clicked to publish before finishing to collect the info

**Comment by bezhanSalleh** [comment]
you are on windows right? the issue might be with the install command same as #443 
1. what happens when you do only `shield:setup` or with flags?
2. if the issue is only with `shield:install` then the manual registeration is also documented
3. with tenancy that option kinda got complicated so what you can do is:
 - `shield:setup --fresh`
 - `shield:install` or manual (only if you wanna enable/disable tenancy or first-install - otherwise skip to only freshen up)
 -  `shield:generate --all`
 - `shield:super-admin`

**Comment by jeffegiovani** [comment]
The same happens to me.
Destroying existent code structure or simply leaving an empty file.

**Comment by CyberPunkCodes** [comment]
For anyone who stumbles here and wants a current working solution, I lay out the steps in my issue. If you have not ran any of the commands yet, you can manually run all of the things necessary. Check out issue #513
