### ISSUE TITLE
Menu Not Appear in Dashboard

### ISSUE THREAD

**Issue by jefriwahyu** [bezhanSalleh/filament-shield#453]
After i create a new role, and when i login user with new role, why menu not showing in dashboard ??
![image](https://github.com/user-attachments/assets/230ee161-ae5b-43b1-af29-63dcece81834)

**Comment by mouchen-qq** [comment]
same problem, also /admin/shield/roles Not Found

**Comment by jefriwahyu** [comment]
its solved, dont know why

**Comment by badgeekluck** [comment]
> its solved, dont know why

any chance to explain how solved it ?

**Comment by andhisan** [comment]
For me running `artisan shield:publish` solved the probrem. I think readme should highlight more this essential command tough

**Comment by bezhanSalleh** [comment]
You basically need to run the `php artisan shield:super-admin` command after the steps mentioned. if you create a user through `filament:user` or `make:filament-user` that user won't have the required role to access or view the resource, becuase after the `shield:install` command shield generates the policy for the resource and enforces it and you haven't given the user that role. It isn't highlighted because this steps assumed how authorization works in general laravel applications. Although the readme can be more descriptive but that requires time which i don't have atm. of course a PR to make it so is always welcomed.

**Comment by h19suporte** [comment]
<img width="1130" alt="image" src="https://github.com/user-attachments/assets/3ad7255f-d5bf-489e-97ec-72c560774b34">

**Comment by Frank22y** [comment]
same problem!

**Comment by marceloxp** [comment]
## This was my approach to achieve this, after having already created a Filament user with the `php artisan make:filament-user`:

```sh
composer require bezhansalleh/filament-shield
php artisan vendor:publish --tag="filament-shield-config"
```

```php
use Spatie\Permission\Traits\HasRoles;
 
class User extends Authenticatable
{
    use HasRoles;
}
```

```sh
php artisan shield:setup
php artisan shield:install admin
php artisan shield:install admin
php artisan shield:super-admin
```

When running `php artisan shield:install admin` the second time it returns a filled table, I myself didn't understand =)

**Comment by mohammedmirzada** [comment]
I had the same issue, and solved it by removing `FilamentShieldPlugin::class` plugin from `AdminPanelProvider.php` then running follwing commands:
`php artisan shield:install`
`php artisan optimize`
Also there is another consideration make sure that plugins are configured correclty in `AdminPanelProvider`.
If you use one plugin you can use:
`->plugin(Plugin::class)`
For more than one plugins:
`->plugins([Plugin1::class, Plugin2::class])`
