### ISSUE TITLE
There is a problem creating the user

### ISSUE THREAD

**Issue by ArtMin96** [bezhanSalleh/filament-shield#52]
There is a problem creating the user. The user in my database does not have a name column. How can I create a super_admin when it asks "Creating Super Admin ..."?

```php
public function up()
{
    Schema::create('users', function (Blueprint $table) {
        $table->id();
        $table->string('first_name');
        $table->string('last_name');
        $table->string('phone')->nullable();
        $table->string('avatar')->nullable();
        $table->string('email')->unique();
        $table->timestamp('email_verified_at')->nullable();
        $table->string('password');
        $table->rememberToken();
        $table->timestamps();
        $table->softDeletes();
    });
}
```

**Comment by HeartlandTechie** [comment]
What about this?   

https://filamentphp.com/docs/2.x/admin/users#configuring-the-name-attribute

**Comment by ArtMin96** [comment]
@HeartlandTechie  It is done but no result

```php
public function getFilamentName(): string
{
    return "{$this->first_name} {$this->last_name}";
}
```

**Comment by bezhanSalleh** [comment]
@ArtMin96 it's not shield related... because the `shield:super-admin` command uses `filament:user` command under the hood for user creation. So for customized the User table you need to handle the user creation yourself by creating seeds... or something... the `shield:super-admin` command only assigns the super-admin role for the already created users and checks if a user exists or not if not will trigger `filament:user`...
