### ISSUE TITLE
How to associate a role to a user?

### ISSUE THREAD

**Issue by zaheen** [bezhanSalleh/filament-shield#82]
I installed shield and created few roles with permissions, I don't see any visual way to assign a role to a user? How can we do that?

**Comment by coolsam726** [comment]
You just use a **CheckboxList** field and assign it a relationship. I use [spatie/laravel-permission](https://spatie.be/docs/laravel-permission/v5/introduction) which gives a Many-to-Many **roles** relationship between users and roles. Here is how I attach roles to users:
In the UserResource I have this in the form schema:
```php
Forms\Components\Section::make('Roles')->schema([
    Forms\Components\CheckboxList::make('roles')->relationship('roles','name'),
])
```
Output in the User's Edit page:
![image](https://user-images.githubusercontent.com/5610289/180698591-e7ca363b-617a-4839-9a84-84077f014c52.png)

**Comment by zaheen** [comment]
Hi @coolsam726 Thank you so much for the tip

**Comment by zaheen** [comment]
> Hi @coolsam726 Thank you so much for the ti

**Comment by bezhanSalleh** [comment]
@zaheen how you associate roles to users is totally up to the dev.
because we can't predict what the dev actually wants.. @coolsam726 uses `CheckboxList`... someone might use `Select::make()->multiple()`.. someone else might use relation manager 🤷🏻‍♂️
shield takes care of filament entities(Resources,Pages,Widgets) and generates permissions and policies.
